@startuml
class User {
  +id: int
  +username: String
  +email: String
  +password: String
  +role: String
  +createdAt: DateTime
}

class Appointment {
  +id: int
  +patentId: int 
  +doctorId: int
  +description: String
  +appointment_date: string
  +status: boolean
  +createdAt: DateTime
}





User "1" --> "0..*" Appointment : writes
 
@enduml