@startuml
left to right direction


rectangle BlogSystem {

  patent --> (View Doctors)
  patent --> (View Appointments)
  patent --> (Book Appointments)
  patent --> (Register)
  patent --> (Login)
  
  doctor --> (Login)
  doctor --> (View Appointments)
  
  Admin --> (Login)
  Admin --> (Maintain Doctors)
  
  (Add Doctors) .> (Maintain Doctors) : extends
  (Edit Doctors) .> (Maintain Doctors) : extends
  (Delete Doctors) .> (Maintain Doctors) : extends
  
}
@enduml